UpdaterDao Unittests
k0r0pt/Project-Tauro pull request #21
Opened 2018-10-22 22:23 UTC by katsadim

# What's this PR for?
Unit tests for UpdaterDao.
This PR is the second part of resolving issue: k0r0pt/Project-Tauro#10

# What to emphasize on when reviewing?
* Now the DB connection is injected into UpdaterDao for easier mocking.
* I took the liberty of introducing Spock framework into the project. Spock will certainly make unit testing easier and fun for sure.
* This will fail for now because there is a need to accept the Linked Pull Request.

# Linked Pull Requests
Repo: k0r0pt/common_build_config#8

2018-10-24 11:35 UTC, sudiptosarkar commented
@katsadim Not sure if Groovy may be the right choice for this. Even if we do keep Groovy tests in there, we need a way for it to add to the coverage. Checkout the [build logs for this PR](https://api.travis-ci.org/v3/job/444841168/log.txt). Your test class didn't run at all... Please resolve this so that `gradle test` runs the groovy tests as well...

Other than that, nicely written... 👍

2018-10-24 11:40 UTC, sudiptosarkar requested changes
@katsadim Not sure if Groovy may be the right choice for this. Even if we do keep Groovy tests in there, we need a way for it to add to the coverage. Checkout the [build logs for this PR](https://api.travis-ci.org/v3/job/444841168/log.txt). Your test class didn't run at all... Please resolve this so that `gradle test` runs the groovy tests as well...

Other than that, nicely written... 👍

2018-10-24 18:31 UTC, katsadim commented
@sudiptosarkar, trust me Spock is one of the best framework for writing unit tests. Groovy make the unit tests much more readable and an absolute beauty. I say that you should give it a try.

The groovy gradle plugin should be applied first in order to run the test. If you accept the linked PR k0r0pt/common_build_config#8 then the spock tests will be enabled.

![image](https://user-images.githubusercontent.com/16381881/47452960-26df3100-d7d4-11e8-9015-e06efa3a996f.png)

2018-10-25 03:20 UTC, sumitsarkar commented
@katsadim I agree that Spock indeed is a very good framework for BDD. But the question is whether introducing a different JVM language just for the sake of introducing BDD makes sense for this project.

Since SQLite requires a single lock to write to the file system, you'd see that the method for insertion of row is `synchronized`. Taking your first idea further, we can simply inject the `UpdaterDao` into the scrapper implementations. That does exactly what you are looking for.
As for testing `UpdaterDao`, the purpose is to test the generated `PreparedStatement`. The easy way would be to extract the logic of the preparation of the statement to a separate function and write simple JUnit tests for validating it.

Having said that, I took your idea and created #23. You can have a look at that. 

I don't see the RoI in introducing a new language and paradigm when the complexity of the project is not very big.

2018-10-25 20:04 UTC, katsadim commented
Imho, introducing a different language is not such a big deal, if it indeed makes testing easier and more enjoyable. Junit compared to Spock is a pain to write and leads to code repetition and really hard to understand tests. As a side note I have seen smaller projects using Spock!

I am glad you liked the dependency injection idea and you took a step even further. 

Just a suggestion here would be to not refer to the concrete class when passing it around but rather declare an interface. This way, when we want for example to save a station in a different storage (DB, cloud, microservice, you name it), then the switch would be easy.

2018-10-26 02:45 UTC, sumitsarkar commented
> Just a suggestion here would be to not refer to the concrete class when passing it around but rather declare an interface. This way, when we want for example to save a station in a different storage (DB, cloud, microservice, you name it), then the switch would be easy.

Agreed! We can introduce the interface when we have varying implementations for storage.

2018-10-26 04:54 UTC, closed without merging