#22 Injecting DAO service through constructor to allow easier mock…
k0r0pt/Project-Tauro pull request #23
Opened 2018-10-24 18:06 UTC by sumitsarkar

# What's this PR for?

This PR is to enable constructor injection of the DB related dependencies. This will allow us to easily mock the injected dependency and then test the scrapper implementation.

# What to emphasize on when reviewing?

* Constructor injections.
* The new abstract class to separate the notion of scrapper and one that "scrapes and saves the data" ( Not sure if this one is actually required. Might be an overkill )

2018-10-25 20:06 UTC, katsadim commented
A small suggestion here: https://github.com/k0r0pt/Project-Tauro/pull/21#issuecomment-433186765

2018-10-26 11:11 UTC, sudiptosarkar requested changes

2018-10-26 11:11 UTC, sudiptosarkar commented on src/main/java/org/koreops/tauro/cli/scraper/AbstractScrapperAndSaver.java
> +public abstract class AbstractScrapperAndSaver extends AbstractScraper {
@sumitsarkar Please rename the class to AbstractScaperAndSaver... 😁

2018-11-02 08:41 UTC, sumitsarkar commented on src/main/java/org/koreops/tauro/cli/scraper/AbstractScrapperAndSaver.java
> +public abstract class AbstractScrapperAndSaver extends AbstractScraper {
Done. Check the new commit

2018-11-02 09:50 UTC, sudiptosarkar approved these changes

2018-11-02 09:51 UTC, merged